import type { VoxelShopClientCore } from './core.js';
import type {
  GenerateUserVerifyUrlParams,
  GenerateUserVerifyUrlResponse,
  VerifyUserParams,
  VerifyUserResponse,
  GetAccountInfoParams,
  GetAccountInfoResponse,
  GetUserIdParams,
  GetUserIdResponse,
} from '../types/index.js';

/** API namespace for actions used by resource managers to identify and verify voxel.shop users. */
export class ManagersApi {
  constructor(private readonly core: VoxelShopClientCore) {}

  /**
   * Generates a URL that verifies a voxel.shop user, e.g. for linking a Discord account. Send the
   * user to the returned URL, then verify the token they receive with {@link ManagersApi.verifyUser}.
   * @remarks To get access to a user's resources instead (e.g. to let them download purchases from your control panel), use {@link PlatformsApi.authorizeUser}.
   */
  async generateUserVerifyURL(params: GenerateUserVerifyUrlParams): Promise<GenerateUserVerifyUrlResponse> {
    return this.core.requestJson<GenerateUserVerifyUrlResponse>('v1/generateUserVerifyURL', {
      service: params.service,
      nonce: params.nonce,
      redirect: params.redirect,
    });
  }

  /** Verifies a voxel.shop user given the token they received from the URL generated by {@link ManagersApi.generateUserVerifyURL}. */
  async verifyUser(params: VerifyUserParams): Promise<VerifyUserResponse> {
    return this.core.requestJson<VerifyUserResponse>('v1/verifyUser', {
      service: params.service,
      nonce: params.nonce,
      token: params.token,
    });
  }

  /** Returns information about a user or a shop. */
  async getAccountInfo(params: GetAccountInfoParams): Promise<GetAccountInfoResponse> {
    return this.core.requestJson<GetAccountInfoResponse>('v1/getAccountInfo', {
      user_id: params.userId,
      shop_id: params.shopId,
    });
  }

  /** Returns a user's id given their username. To verify a user's id, use {@link ManagersApi.verifyUser} instead. */
  async getUserId(params: GetUserIdParams): Promise<GetUserIdResponse> {
    return this.core.requestJson<GetUserIdResponse>('v1/getUserId', {
      username: params.username,
    });
  }
}
