name: Publish

on:
    push:
        tags:
            - "v*"

permissions:
    id-token: write
    contents: read

jobs:
    test:
        name: Test
        uses: ./.github/workflows/test.yml
        permissions:
            contents: read
        with:
            ref: ${{ github.ref }}

    publish:
        name: Publish to npm
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Set up pnpm
              uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

            - name: Set up Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Publish to npm
              run: pnpm publish --no-git-checks

    release:
        name: GitHub Release
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Create draft release
              uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
              with:
                  draft: true
                  generate_release_notes: true
                  token: ${{ secrets.GH_PAT }}
